project_id = "effhelwpanlnfmeguvek"

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.send-contact-notification]
verify_jwt = false

[functions.admin-list-subscriptions]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
